// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import RecipeModalsController from "./recipe_modals_controller.js"
application.register("recipe-modals", RecipeModalsController)

import CollapseController from "./collapse_controller.js"
application.register("collapse", CollapseController)




